Initial commit for atSpoke integration
JupiterOne/graph-atspoke pull request #1
Opened 2021-02-16 19:25 UTC by kevincasey1222

This integration uses Axios and the Jupiter One integration template. 

It gathers 6 types of objects - Account, Users, Teams (J1 UserGroup), Requests (J1 Record), RequestTypes (J1 Configuration), and Webhooks (J1 ApplicationEndpoint). All but Webhooks support pagination (the atSpoke API doesn't support pagination for GET /webhooks, but these are outbound APIs - there shouldn't be that many).

The config file asks for an API_KEY and NUM_REQUESTS param which sets the number of Requests (essentially helpdesk tickets) to pull into the system, both OPEN and RESOLVED status. The atSpoke API returns the most recent X numbers of requests, set by this param. These Records in J1 are set with partial:true so they can accumulate. Optionally, you can set NUM_REQUESTS to 0, in which case the integration will not pull Requests at all, nor will it pull RequestTypes. (RequestTypes are also set partial:true, so no problem if old entries are in the system).

Tests use a recording and compare it to a snapshot, both drawn from a test account I made on atSpoke.

2021-02-16 19:48 UTC, kevincasey1222 commented
I'm confused as to why the build test is saying that the snapshots don't match. I've run "yarn run prepush -u" and "yarn test -u" here. Also, all the tests pass when I push. What is different about the CICD environment?

2021-02-18 21:35 UTC, kevincasey1222 commented
Alright, snapshot solved. Not sure why that needed separate wrangling, but it is wrangled.

2021-02-24 02:28 UTC, aiwilliams requested changes
Thanks @kevincasey1222! I made some inline comments, but these ones here couldn't be attached to a file. I think most of this will be pretty quick to fix.

1. [`docs/jupiterone.md`](https://github.com/JupiterOne/graph-atspoke/pull/1/files#diff-5aa6cbd3ecfc78d03ab6ffe94dac2c4ff3081fd66f15b999d7691ddad293b547) has a number of `TODO` statements in it that need to be addressed. Consider the Google integration as [an example](https://github.com/JupiterOne/graph-google/blob/master/docs/jupiterone.md).
2. We currently use Yarn for package installation. I see there is a [`package-lock.json`](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json), which is produced by NPM. I think the latest version of NPM can use a `yarn.lock` file, but I [don't think it works the other way](https://classic.yarnpkg.com/blog/2018/06/04/yarn-import-package-lock/).

2021-02-24 02:28 UTC, aiwilliams commented on README.md
> +## Development Environment
@kevincasey1222 the integration template was changed between the time that you first started this work and the time this PR was created (I think). We'd like to have the README.md the same on all integrations, which will point to other documents that describe how integrations work, and any unique things will be in the `docs/` directory. I think that means:

1. This file can simply be reverted.
2. "Getting an API Key from atSpoke" and "Configuring the number of requests desired in your JupiterOne graph" in here can be moved to `docs/development.md`.

2021-02-24 02:28 UTC, aiwilliams commented on src/types.ts
> +  numRequests: string;
It will be important to document the meaning and impact of changing this variable. We are going to make it visible in the UI as well (when we deploy it), so this will aid writing the help text for the field.

```suggestion
  /**
   * The number of recent requests to ingest.
   *
   * Requests are Record entities. The collection size will grow indefinitely. This allows for limiting the number
   * of recently created/changed requests to ingest whenever the integration executes. This should be set to
   * a value that correlates to the execution interval of the integration and the expected number of requests
   * that would have been created/changed between executions.
   */
  numRequests: string;
```

2021-02-24 02:28 UTC, aiwilliams commented on src/validateInvocation.test.ts
> +      numRequests: '0',
It would be good to test what happens when `numRequests` is `undefined`, `-1000`, `abc`, etc. since this will be configured by users.

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/index.test.ts
> +  //expect(webhooks.length).toBeGreaterThan(0);
I think it would be good to make this say we ingested at least one. This will mean the development/test account would have to have one setup of course, but that's a good thing should someone need to re-record responses.

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/account.ts
> +export const ACCOUNT_ENTITY_KEY = 'at_spoke_account';
I'm going to update the template project....

We're working toward using this naming pattern for the constant that defines the key for `setData/getData` entries, to clarify that this is meant to be orthogonal to entities and their `_type` values. Then, all things stuck in `setData/getData` will be easily found by `DATA_` search.

```suggestion
export const DATA_ACCOUNT_ENTITY = 'DATA_ACCOUNT_ENTITY';
```

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/account.ts
> +          _type: ACCOUNT_ENTITY_KEY,
With the aforementioned move to `DATA_ACCOUNT_ENTITY`, it will become clear that this should be a different variable with the value `at_spoke_account`.

This is not necessary to address in this PR, but wanted you to be aware, and I've got a task to update the integration-template...

We're moving toward this pattern for defining the things ingested and referencing them in the step metadata: https://github.com/JupiterOne/graph-azure/blob/master/src/steps/resource-manager/network/constants.ts

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/account.ts
> +          _type: ACCOUNT_ENTITY_KEY,
With the aforementioned move to `DATA_ACCOUNT_ENTITY`, it will become clear that this should be a different variable with the value `at_spoke_account`.

This is not necessary to address in this PR, but wanted you to be aware, and I've got a task to update the integration-template...

We're moving toward this pattern for defining the things ingested and referencing them in the step metadata: https://github.com/JupiterOne/graph-azure/blob/master/src/steps/resource-manager/network/constants.ts

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/requests.ts
> +            partial: true,
This is a value that should be on the metadata in the step.

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/requests.ts
> +            partial: true,
This is a value that should be on the metadata in the step.

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/requests.ts
> +      },
Here is where the `partial: true` value would go.

Note that the relationships between the account and request would also need to be marked as `partial: true`. This flag is metadata informing the synchronization system that there is no need to do set comparison (leading to deletes of objects which are in the graph but not represented in the newly uploaded set), which is true for these relationships because the integration will never upload a complete set, just as it does not for the request Record entities.

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/__recordings__/steps_741716276/recording.har
> +              "value": "AtFbNFj2hvzt7pGkg_zgW7ksihiFaVrVwttLKxU2oRVU="
The recording setup code should add this as a sensitive header key so that the value is redacted from the recordings. Also, it is now necessary to delete this API key from the provider and generate a new one.

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/__recordings__/steps_741716276/recording.har
> +            "text": "{\"results\":[{\"authentication\":{\"type\":\"client_secret\",\"clientSecret\":\"EhKHiEzCCbd7wSRyByU1TISyAeuS8nEh3ThwGqC2h2c=\"},\"enabled\":true,\"topics\":[\"request.created\"]
This may need some redaction work since it contains a secret looking thing. When we don't redact these, even if they're not terribly sensitive because these are dev accounts, we end up getting hackers saying that we have a leak, and we have to treat it as super important, which can be a hassle/unnecessary scare. That said...

Is this a value that can be configured when setting up the webhook? Perhaps it could be set to something like "not-real-very-not-sensitive-actually"?

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/__snapshots__/index.test.ts.snap
> +      ],
So, I'm sorry about this, we need to do something in the SDK to prevent this... just created https://github.com/JupiterOne/sdk/issues/424.

Graph objects (entities, relationships) cannot have properties that are objects, nor Arrays of objects. The synchronization system will reject this as an invalid entity.

This property can, I think, simply be dropped at this time. Perhaps we could have another change later on where this drives a relationship to each organization entity the user has a membership in, so that an analyst can see where their users are accessing multiple orgs with their user accounts?

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/__snapshots__/index.test.ts.snap
> +            "agentList": Array [
Let's drop `agentList` from the raw data. These should be the raw data of the entities themselves.

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/__snapshots__/index.test.ts.snap
> +            "users": Array [
Let's drop `users` from the raw data. These should be the raw data of the user entities.

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/__snapshots__/index.test.ts.snap
> +              "clientSecret": "EhKHiEzCCbd7wSRyByU1TISyAeuS8nEh3ThwGqC2h2c=",
This will need to be redacted from the raw data.

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/__snapshots__/index.test.ts.snap
> +            "requestTypeInfo": Object {
I think we should drop this from this raw data. It should be the raw data of the request types themselves. Otherwise, we'll repeat all this throughout every request entity.

Seems like their API is generous with the data it returns ATM...

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/__snapshots__/index.test.ts.snap
> +      "owner": "602585518843b90007eeda34",
Let's create an Issue to build a relationship to owner user entities.

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/__snapshots__/index.test.ts.snap
> +      "requester": "601da2951d25d80007bf87d2",
Let's create an Issue to build a relationship to requester user entities.

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/__snapshots__/index.test.ts.snap
> +            "tags": Array [],
Let's add an Issue to convert these to `tag.<name>` properties on the entity.

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/access.ts
> +        _type: 'at_spoke_account',
The `fetch-account` step creates this entity, so it can be removed from this step's metadata.

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/access.ts
> +        _class: 'Account',
The `fetch-account` step creates this entity, so it can be removed from this step's metadata.

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/access.ts
> +      },
The `fetch-users` step creates this entity, so it can be removed from this step's metadata.

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/access.ts
> +    name: 'Fetch UserGroups',
I *think* these names tend to use the terminology of the provider, so that in the job logs presented to the users, they see that the atSpoke Teams have been processed.
```suggestion
    id: 'fetch-teams',
    name: 'Fetch Teams',
```

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/access.ts
> +      },
The `fetch-users` step creates this relationship, so it can be removed from this step's metadata.

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/requests.ts
> +      },
The `fetch-account` step creates this entity, so it can be removed from this step's metadata.

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/requests.ts
> +      },
The `fetch-account` step creates this entity, so it can be removed from this step's metadata.

2021-02-24 02:28 UTC, aiwilliams commented on src/steps/webhooks.ts
> +      },
The `fetch-account` step creates this entity, so it can be removed from this step's metadata.

2021-02-25 22:41 UTC, kevincasey1222 commented on README.md
> +## Development Environment
Done. Thanks for the clarity.

2021-02-26 00:13 UTC, kevincasey1222 commented on src/validateInvocation.test.ts
> +      numRequests: '0',
Many tests added to parser. Thanks!

2021-02-26 00:13 UTC, kevincasey1222 commented on src/steps/account.ts
> +export const ACCOUNT_ENTITY_KEY = 'at_spoke_account';
Implemented.

2021-02-26 00:13 UTC, kevincasey1222 commented on src/steps/account.ts
> +          _type: ACCOUNT_ENTITY_KEY,
Implemented

2021-02-26 00:16 UTC, kevincasey1222 commented on src/steps/requests.ts
> +      },
Thanks, @aiwilliams . So, when I got to add partial: true here, it tells me that partial does not exist as a known property in StepEntityMetadata.ts.

2021-02-26 00:24 UTC, kevincasey1222 commented on src/steps/index.test.ts
> +  //expect(webhooks.length).toBeGreaterThan(0);
Done.

2021-02-26 00:25 UTC, kevincasey1222 commented on src/steps/account.ts
> +          _type: ACCOUNT_ENTITY_KEY,
Implemented.

2021-02-26 00:27 UTC, kevincasey1222 commented on src/steps/__snapshots__/index.test.ts.snap
> +              "clientSecret": "EhKHiEzCCbd7wSRyByU1TISyAeuS8nEh3ThwGqC2h2c=",
Done.

2021-02-26 00:27 UTC, kevincasey1222 commented on src/steps/__recordings__/steps_741716276/recording.har
> +            "text": "{\"results\":[{\"authentication\":{\"type\":\"client_secret\",\"clientSecret\":\"EhKHiEzCCbd7wSRyByU1TISyAeuS8nEh3ThwGqC2h2c=\"},\"enabled\":true,\"topics\":[\"request.created\"]
Done.

2021-02-26 00:28 UTC, kevincasey1222 commented on src/steps/__recordings__/steps_741716276/recording.har
> +            "text": "{\"results\":[{\"authentication\":{\"type\":\"client_secret\",\"clientSecret\":\"EhKHiEzCCbd7wSRyByU1TISyAeuS8nEh3ThwGqC2h2c=\"},\"enabled\":true,\"topics\":[\"request.created\"]
And yes, the only way to make a webhook is via REST API, so I just did that once in the dev acct so I could pull it down. In this case, I just updated it in the recording and snapshot.

2021-02-26 00:28 UTC, kevincasey1222 commented on src/steps/__recordings__/steps_741716276/recording.har
> +              "value": "AtFbNFj2hvzt7pGkg_zgW7ksihiFaVrVwttLKxU2oRVU="
Done.

2021-02-26 00:46 UTC, kevincasey1222 commented on src/steps/__snapshots__/index.test.ts.snap
> +      ],
Property dropped.

2021-02-26 01:15 UTC, kevincasey1222 commented on src/steps/__snapshots__/index.test.ts.snap
> +            "agentList": Array [
Done.

2021-02-26 01:16 UTC, kevincasey1222 commented on src/steps/__snapshots__/index.test.ts.snap
> +            "users": Array [
Done.

2021-02-26 01:16 UTC, kevincasey1222 commented on src/steps/__snapshots__/index.test.ts.snap
> +            "requestTypeInfo": Object {
Done.

2021-02-26 01:25 UTC, kevincasey1222 commented on src/steps/access.ts
> +    name: 'Fetch UserGroups',
True. Done.

2021-02-26 01:40 UTC, kevincasey1222 commented on src/steps/access.ts
> +    name: 'Fetch UserGroups',
Agree. Done.

2021-02-26 01:59 UTC, kevincasey1222 commented
Thanks for the detailed code review, @aiwilliams! I've fixed most of the items, made a few improvements here and there, and created issues for the three where you recommended that.

The only thing not addressed is the partial: true. You said that shouldn't be an entity property but rather a metadata entry? But when I try to add it as a metadata entry it says that the property `partial` is not a valid option in StepEntityMetadata.ts.

2021-03-01 19:17 UTC, aiwilliams reviewed
Thanks a ton for addressing all that @kevincasey1222 👍 

Re: `partial`, check out https://github.com/JupiterOne/sdk/pull/371/files#diff-515bb61dc6b28aad92c0bd1f754a5d59808f4603622cc64de09f0814ed94830dR90. Hopefully that clears things up a bit.

It looks like `test/recording.ts` was not changed to automatically redact sensitive things in new recordings. Did you do that manually? That's okay for this PR I think, just want to be sure I didn't miss anything. We can make it automatic when the recordings are changed in the future.

2021-03-01 19:17 UTC, aiwilliams commented on docs/jupiterone.md
> +## atSpoke + JupiterOne Integration Benefits
Excellent work on this file, thanks a ton!

2021-03-01 19:17 UTC, aiwilliams commented on src/validateInvocation.test.ts
> +});
🔥 TIP 🚒 : check out https://jestjs.io/docs/en/api#testeachtablename-fn-timeout

2021-03-01 20:48 UTC, kevincasey1222 commented
Hi @aiwilliams ! 

You're right, I updated the recording manually. I hadn't realized there was a way to automatically redact sensitive headers in the recordings. I updated the invocation to redact `api-key` automatically, which was most of the issue. However, the webhooks have a `client-secret` property in the response body returned by the API when we get webhooks, so those will have to be manually redacted in the future. That said, webhooks can only be created by the API also, so in the future, if we create a webhook in a dev acct, we can just set the client-secret property to "not-really-a-secret" or "redacted_secret" and then we won't have to do any manual updating of the recording.

I also figured out the `partial: true` flag - it was a problem because the integration template was using sdk 3.1.0 by default. I updated to 5.8.0 and all was good. In moving `partial` from being an entity property to a metadata flag, I also had to update the snapshot.

All should be good now.

2021-03-01 21:46 UTC, aiwilliams approved these changes
Thanks @kevincasey1222 !

2021-03-01 21:46 UTC, merged